### ISSUE TITLE
Signing in after Sign Up in local development redirects back to Sign Up and causes infinite loop reloading with "?refresh=true"

### ISSUE THREAD

**Issue by polooner** [aietal/isaac#56] opened 2023-12-28 10:28 UTC
I am trying to get local development set up and encounter a problem singing into the application.

1. After successful installation of packages, start the local dev environment with ```npm run dev```
2. Try to sign up with e-mail, wait for the e-mail and click "Confirm your mail".
3. The website redirects to sign up and runs an infinite loop

This error shows up in the console:

![Image 12-28-23 at 12 07 PM](https://github.com/aietal/isaac/assets/114031148/78742032-61c7-4d94-aff2-5d14ef9175d4)

**Comment by eimenhmdt** [comment] 2024-01-03 22:18
Hey @polooner , sorry for the late response, I had some personal stuff going on. So, the refresh=true query param is a hacky fix for an issue related to google authentication. 

Silly me, I think I know where the problem comes from. There is a missing instruction in the readme. You need to define a database function called "create_profile_for_user" with the following definition:

```
begin
  insert into public.profile(id, email)
  values(new.id, new.email);
  
  return new;
end;
```

Let me know whether this resolves the issue. Thanks a lot for bringing this up!

**Comment by eimenhmdt** [comment] 2024-01-08 08:03
@polooner I'm closing this issue since the actual problem wasn't caused by the redirect.

**Closed by eimenhmdt** 2024-01-08 08:03 UTC
